library(sf)

# Clean the environment
rm(list=ls())

# Additional base steps 
sf_use_s2(FALSE) # solves problems with latest version of sf for st_as_sf()

ABALONES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/ABALONES.shp")
AMPHIBIANS_PART1 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/AMPHIBIANS_PART1.shp")
AMPHIBIANS_PART2 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/AMPHIBIANS_PART2.shp")
BIRCHES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/BIRCHES.shp")
BLENNIES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/BLENNIES.shp")
BONEFISHES_TARPONS_LADYFISHES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/BONEFISHES_TARPONS_LADYFISHES.shp")
Buffers <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/Buffers.shp")
BUTTERFLYFISH_ANGELFISH_ALLIES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/BUTTERFLYFISH_ANGELFISH_ALLIES.shp")
CARANGIFORM_FISHES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/CARANGIFORM_FISHES.shp")
CLUPEIFORMES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/CLUPEIFORMES.shp")
CONE_SNAILS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/CONE_SNAILS.shp")
EELS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/EELS.shp")
FW_CRABS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_CRABS.shp")
FW_CRAYFISH <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_CRAYFISH.shp")
FW_FISH_PART1 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_FISH_PART1.shp")
FW_FISH_PART2 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_FISH_PART2.shp")
FW_MOLLUSCS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_MOLLUSCS.shp")
FW_ODONATA <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_ODONATA.shp")
FW_OTHER_PART1 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_OTHER_PART1.shp")
FW_OTHER_PART2 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_OTHER_PART2.shp")
FW_OTHER_PART3 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_OTHER_PART3.shp")
FW_OTHER_PART4 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_OTHER_PART4.shp")
FW_PLANTS_PART1 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_PLANTS_PART1.shp")
FW_PLANTS_PART2 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_PLANTS_PART2.shp")
FW_SHRIMPS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/FW_SHRIMPS.shp")
GROUPERS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/GROUPERS.shp")
HAGFISH <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/HAGFISH.shp")
LOBSTERS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/LOBSTERS.shp")
MAGNOLIAS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MAGNOLIAS.shp")
MAMMALS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MAMMALS.shp")
MANGROVES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MANGROVES.shp")
MAPLES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MAPLES.shp")

MARINEFISH_PART1 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MARINEFISH_PART1.shp")
MARINEFISH_PART2 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MARINEFISH_PART2.shp")
MARINEFISH_PART3 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MARINEFISH_PART3.shp")
MARINEFISH_PART4 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MARINEFISH_PART4.shp")
MARINEFISH_PART5 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MARINEFISH_PART5.shp")
MARINEFISH_PART6 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/MARINEFISH_PART6.shp")

PUFFERFISHES_AND_RELATIVES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/PUFFERFISHES_AND_RELATIVES.shp")
REEF_FORMING_CORALS_PART1 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/REEF_FORMING_CORALS_PART1.shp")
REEF_FORMING_CORALS_PART2 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/REEF_FORMING_CORALS_PART2.shp")
REEF_FORMING_CORALS_PART3 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/REEF_FORMING_CORALS_PART3.shp")
REPTILES_PART1 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/REPTILES_PART1.shp")
REPTILES_PART2 <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/REPTILES_PART2.shp")
SEAGRASSES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/SEAGRASSES.shp")
SHARKS_RAYS_CHIMAERAS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/SHARKS_RAYS_CHIMAERAS.shp")
STURGEONS_PADDLEFISHES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/STURGEONS_PADDLEFISHES.shp")
SYNGNATHIFORM_FISHES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/SYNGNATHIFORM_FISHES.shp")
TEAS <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/TEAS.shp")
TREES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/TREES.shp")
TUNAS_BILLFISHES_SWORDFISH <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/TUNAS_BILLFISHES_SWORDFISH.shp")
WRASSES_PARROTFISHES <- st_read("/Users/batume/Documents/R/GAL_git/prep/BD_SP/WRASSES_PARROTFISHES.shp")